import Head from 'next/head'
import Header from '../components/Header'
import Section01 from '../components/Section01'

export default function Portfolio() {
  return (
    <div >
      <Head>
        <title>Next Props</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section className='px-4 mt-24 w-full' id='portfolio'>
        <h2 className=''>Portfolio</h2>  
      </section>

    </div>
  )
}